=== anish-2903/AndroidStudio/Notes/Day 5/Test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="lang" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="author" type="xs:string" />
                            <xs:element name="year" type="xs:string" />
                            <xs:element name="price" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="category" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anish-2903/AndroidStudio/Notes/Day 5/Test.xml
<!-- <friendsList>
    <friends>
        <name>Alex</name>
    </friends>
    <friends>
        <name>Tamori</name>
    </friends>
    <friends>
        <name>Maven</name>
    </friends>
    <bestFriend>
        <name>Gavin</name>
    </bestFriend>
</friendsList> -->


<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Test.xsd">
  <book category="fiction">
    <title lang="en">Harry Potter</title>
    <author>J.K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
  <book category="non-fiction">
    <title lang="en">The Elements of Style</title>
    <author>William Strunk Jr.</author>
    <year>1999</year>
    <price>9.99</price>
  </book>
</bookstore>
